seg_ade20k:
  file: "eval_segmentation.py"
  train_dataset_name: "custom://ADE20K?split='training'"
  test_dataset_name: "custom://ADE20K?split='validation'"
  ignore_labels: [0,255]  # For most datasets it's 255, but for ADE20K it's 0
  classifiers_kwargs:
    knn:
      dtype: bfloat16
seg_voc2012:
  file: "eval_segmentation.py"
  train_dataset_name: "custom://VOC2012?split='train'"
  test_dataset_name: "custom://VOC2012?split='val'"
  ignore_labels: [255]  # For most datasets it's 255, but for ADE20K it's 0
  classifiers_kwargs:
    knn:
      dtype: bfloat16